// Generated by CoffeeScript 1.9.1
var estacionamientos, express, request, router;

express = require('express');

request = require('request');

router = express.Router();

estacionamientos = require('./routes-estacionamientos')(router);


/* GET home page. */

router.get('/', function(req, res, next) {
  res.send('EMX')

}).get('/go', function(req, res) {
  return request('http://datos.labcd.mx/api/action/datastore_search?resource_id=4366bf30-01eb-4fa0-9f2a-c74153ec2b79&limit=5', function(error, response, body) {
    if (!error && response.statusCode === 200) {
      return res.send(body);
    }
  });
});

module.exports = router;
